apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.global.name }}-service
  namespace: {{ .Values.global.namespace }}
  annotations:
      prometheus.io/scrape: !!str {{ .Values.prometheus.scrape }}
      prometheus.io/path:   !!str {{ .Values.prometheus.path }}
      prometheus.io/port:   !!str {{ .Values.service.ports.port }}
spec:
  selector:
    app: {{ .Values.global.name }}-server
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.ports.port }}
      targetPort: {{ .Values.service.ports.targetPort }}
      name: gui
    - port: 50000
      targetPort: 50000
      name: slaves