kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: local-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.global.name }}-pv-volume
  labels:
    type: local
spec:
  storageClassName: local-storage
  claimRef:
    name: {{ .Values.global.name }}-pv-claim
    namespace: {{ .Values.global.namespace }}
  capacity:
    storage: {{ .Values.volume.totalStorage }}
  accessModes:
    - ReadWriteOnce
  local:
    path: /mnt
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: node.kubernetes.io/instance-type
          operator: In
          values:
          - {{ .Values.global.nodeType }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.global.name }}-pv-claim
  namespace: {{ .Values.global.namespace }}
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.volume.claimedStorage }}